const fcActionTypes = {
    SET_FC_POINTER: 'SET_FC_POINTER',
    SET_FCP_POINTER: 'SET_FCP_POINTER',
    SET_FC_NULL: 'SET_FC_NULL',
    SET_FCP_NULL: 'SET_FCP_NULL',
    SET_FC_IS_CONNECTED: 'SET_FC_IS_CONNECTED', 
    SET_FC_IS_SUBSCRIBED_TO_IMU: 'SET_FC_IS_SUBSCRIBED_TO_IMU',
};

export default fcActionTypes;