const wayPointTypes = {
    SET_BOUNDING_BOX: 'SET_BOUNDING_BOX',
    SET_BOUNDING_BOX_NULL: 'SET_BOUNDING_BOX_NULL',
    SET_POINT_CLOUD: 'SET_POINT_CLOUD',
    SET_POINT_CLOUD_NULL:'SET_POINT_CLOUD_NULL',
};

export default wayPointTypes;