const wayPointTypes = {
    SET_POLYGON: 'SET_POLYGON',
    SET_POLYGON_NULL: 'SET_POLYGON_NULL',
    SET_POINT_CLOUD: 'SET_POINT_CLOUD',
    SET_POINT_CLOUD_NULL:'SET_POINT_CLOUD_NULL',
};

export default wayPointTypes;